// This file was autogenerated by deps/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('src/gli/capture/capture.js', ['gli.capture'], ['gli.capture.WebGLCapturingContext', 'gli.capture.transports.DebugTransport', 'gli.util.TimerController', 'goog.array']);
goog.addDependency('src/gli/capture/extension.js', ['gli.capture.Extension'], ['goog.Disposable']);
goog.addDependency('src/gli/capture/extensions/gli_debugger.js', ['gli.capture.extensions.GLI_debugger'], ['gli.capture.Extension']);
goog.addDependency('src/gli/capture/resource.js', ['gli.capture.Resource'], []);
goog.addDependency('src/gli/capture/resourcecache.js', ['gli.capture.ResourceCache'], []);
goog.addDependency('src/gli/capture/resources/program.js', ['gli.capture.resources.Program', 'gli.capture.resources.UniformInfo'], ['gli.capture.Resource']);
goog.addDependency('src/gli/capture/transport.js', ['gli.capture.Transport'], ['goog.Disposable']);
goog.addDependency('src/gli/capture/transports/debugtransport.js', ['gli.capture.transports.DebugTransport'], ['gli.capture.Transport']);
goog.addDependency('src/gli/capture/webglcapturingcontext.js', ['gli.capture.WebGLCapturingContext'], ['gli.capture.extensions.GLI_debugger', 'gli.capture.resources.Program', 'gli.data.Call', 'gli.data.Frame', 'gli.data.SessionInfo', 'goog.Disposable', 'goog.array', 'goog.asserts', 'goog.object']);
